-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: c8a1c91c762b8e24fdc5a33455ec10662f523328
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: check-xml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
        args:
        - --exclude=docs/conf.py --ignore F401,F811 tests
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: d044ff27300a6dc8b1a56cd22552e3a810dc6f49
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
