sudo: false
language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
  - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
install:
- source tests/travis_install.sh
- pip install git+https://github.com/behave/behave
- pip install -r test-requirements.txt
before_script:
- git config --global user.email "william.usher@ouce.ox.ac.uk"
- git config --global user.name "Will Usher"
script:
- python setup.py develop
- python setup.py test
- python setup.py behave_test
after_success:
- if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
- apt
notifications:
  email: false
addons:
  apt:
    packages:
    - glpk
deploy:
  provider: pypi
  user: willu47
  password:
    secure: YBOLdKnKWIIKozbcrmzZZnhT9fUT3JOUVXvJFiskG8iNSLlIbEh0l4J8aZyxVU3xdT+BgL8m0lQBTbiegffvynWtQ/GtN9WMgVWDl/Z+OFEkV0zCa6XVr0ThJtVRItzn4YmEfHmFJXudVMP5Zyiuz9t14O5NuieyBHAIML7L1XEZtkvWOjSfSgyOhWSauB08LiRVvZEWDWu1b9PTzrRyQ7Ynv9Wdq/bLK8oBjeBwV7O9JdQf29PtnP3Zkr2RB8SkmziD0ZDvg3WDfUbqRe30bed8fL9WnTDvHGBL/Ynl1VHObtsN6eBlDErUjnVuI0HRfjtubDORWlZx97mU2jmK0Kas99kAIzBCmgRv1svQa8U8tX4pQ9XsIq648G8ZLgn2coyPPDt2K6MMHtr8XSRAXA+bVu8B6betYa3mLeuwBcGBinpzPm0Omx6kDf46wZ9rzaI1B1dQ0YrK/N9UDtlMGNJ2Z3A66hmOdxx2I2KAkZqI4k4S15RpwZ1MmlBXdjWUJhHsKCHk0Ccj5hzZeHA8+HnMpg4oBMhD8d9vvQg66w5htHledgTglhpbDqUw/KF1HsJHf1Bd8dGv5YJH0NbFdzPzLCWadU8jMvgLFrmX1AqZBewJSDUJOPEo9Avk3DwkOR3T6auSupBp4tRvL26ha6vzlTxgXV3CSEDKm7mf5SI=
  on:
    tags: true
    distributions: sdist bdist_wheel
